''' <summary>
''' Represents a single entry in the resource access log.
''' Used for generating the Monthly Access Summary report.
''' Each record tracks one user's access of one resource at a point in time.
''' </summary>
Public Class AccessLog

    ''' <summary>Primary key - auto-generated by SQL Server.</summary>
    Public Property LogID As Integer

    ''' <summary>Foreign key to tblUsers.</summary>
    Public Property UserID As Integer

    ''' <summary>Display name of the user (populated via JOIN).</summary>
    Public Property UserFullName As String

    ''' <summary>Foreign key to tblResources.</summary>
    Public Property ResourceID As Integer

    ''' <summary>Title of the accessed resource (populated via JOIN).</summary>
    Public Property ResourceTitle As String

    ''' <summary>Category name of the resource (populated via JOIN).</summary>
    Public Property CategoryName As String

    ''' <summary>Date and time the resource was accessed.</summary>
    Public Property AccessDate As DateTime

    ''' <summary>
    ''' Type of access event.
    ''' Valid values: "View" | "Bookmark" | "Download"
    ''' </summary>
    Public Property AccessType As String

End Class

''' <summary>
''' A summary record used for the Monthly Access Summary report.
''' Aggregated from tblAccessLog via vwMonthlyAccessSummary.
''' </summary>
Public Class MonthlyAccessSummary

    ''' <summary>Year portion of the access period.</summary>
    Public Property AccessYear As Integer

    ''' <summary>Month number (1-12).</summary>
    Public Property AccessMonth As Integer

    ''' <summary>Display name of the month (e.g., "January").</summary>
    Public Property MonthName As String

    ''' <summary>ID of the resource being summarized.</summary>
    Public Property ResourceID As Integer

    ''' <summary>Title of the resource being summarized.</summary>
    Public Property ResourceTitle As String

    ''' <summary>Category of the resource.</summary>
    Public Property CategoryName As String

    ''' <summary>Type of the resource (E-Book, Video, etc.).</summary>
    Public Property ResourceType As String

    ''' <summary>Total number of access events for this resource in this period.</summary>
    Public Property TotalAccesses As Integer

    ''' <summary>Number of distinct users who accessed this resource.</summary>
    Public Property UniqueUsers As Integer

    ''' <summary>Returns a formatted period string for display.</summary>
    Public ReadOnly Property Period As String
        Get
            Return $"{MonthName} {AccessYear}"
        End Get
    End Property

End Class
