''' <summary>
''' Represents a student's bookmarked resource for quick future access.
''' A student can bookmark any resource once (enforced by DB unique constraint).
''' </summary>
Public Class Bookmark

    ''' <summary>Primary key - auto-generated by SQL Server.</summary>
    Public Property BookmarkID As Integer

    ''' <summary>Foreign key to tblUsers - the student who bookmarked.</summary>
    Public Property UserID As Integer

    ''' <summary>Foreign key to tblResources - the bookmarked resource.</summary>
    Public Property ResourceID As Integer

    ''' <summary>Title of the bookmarked resource (populated via JOIN).</summary>
    Public Property ResourceTitle As String

    ''' <summary>Category of the bookmarked resource (populated via JOIN).</summary>
    Public Property CategoryName As String

    ''' <summary>Resource type (populated via JOIN).</summary>
    Public Property ResourceType As String

    ''' <summary>URL of the bookmarked resource (populated via JOIN).</summary>
    Public Property ResourceURL As String

    ''' <summary>Date and time when the bookmark was saved.</summary>
    Public Property DateBookmarked As DateTime

End Class
