''' <summary>
''' Represents a resource category used to classify educational materials.
''' Examples: Mathematics, Programming, Science and Technology.
''' </summary>
Public Class Category

    ''' <summary>Primary key - auto-generated by SQL Server.</summary>
    Public Property CategoryID As Integer

    ''' <summary>Unique display name of the category.</summary>
    Public Property CategoryName As String

    ''' <summary>Short description of what this category covers.</summary>
    Public Property Description As String

    ''' <summary>Soft-delete flag - inactive categories are hidden from selection.</summary>
    Public Property IsActive As Boolean

    ''' <summary>Date and time the category was created.</summary>
    Public Property DateCreated As DateTime

    ''' <summary>
    ''' Number of resources belonging to this category.
    ''' Populated by aggregate queries in the DAL - not stored in DB.
    ''' </summary>
    Public Property ResourceCount As Integer

    ''' <summary>Returns the category name for binding to ComboBox/ListBox controls.</summary>
    Public Overrides Function ToString() As String
        Return CategoryName
    End Function

End Class
