''' <summary>
''' Represents a single open educational resource in the EduVault library.
''' Resources can be e-books, videos, modules, references, or articles.
''' Aligned with UN SDG 4 - Quality Education.
''' </summary>
Public Class Resource

    ''' <summary>Primary key - auto-generated by SQL Server.</summary>
    Public Property ResourceID As Integer

    ''' <summary>Descriptive title of the educational resource.</summary>
    Public Property Title As String

    ''' <summary>Detailed description of the resource and its contents.</summary>
    Public Property Description As String

    ''' <summary>Foreign key to tblCategories.</summary>
    Public Property CategoryID As Integer

    ''' <summary>Display name of the category (populated via JOIN).</summary>
    Public Property CategoryName As String

    ''' <summary>Specific subject area within the category (e.g., "Calculus", "Web Development").</summary>
    Public Property SubjectArea As String

    ''' <summary>
    ''' Type of educational resource.
    ''' Valid values: "E-Book" | "Video" | "Module" | "Reference" | "Article"
    ''' </summary>
    Public Property ResourceType As String

    ''' <summary>URL link to the resource (for web-based resources).</summary>
    Public Property URL As String

    ''' <summary>Local or network file path (for uploaded files).</summary>
    Public Property FilePath As String

    ''' <summary>
    ''' Target education level.
    ''' Valid values: "Beginner" | "Intermediate" | "Advanced"
    ''' </summary>
    Public Property EducationLevel As String

    ''' <summary>Comma-separated keywords for searchability.</summary>
    Public Property Tags As String

    ''' <summary>Foreign key to tblUsers - who added this resource.</summary>
    Public Property AddedBy As Integer

    ''' <summary>Full name of the user who added this resource (populated via JOIN).</summary>
    Public Property AddedByName As String

    ''' <summary>Date and time the resource was added to the library.</summary>
    Public Property DateAdded As DateTime

    ''' <summary>Soft-delete flag. False = archived, not visible to students.</summary>
    Public Property IsActive As Boolean

    ''' <summary>Total number of times this resource has been accessed (viewed).</summary>
    Public Property ViewCount As Integer

    ' ─────────────────────────────────────────────────────────────
    ' V2 ENGAGEMENT & VERSIONING
    ' ─────────────────────────────────────────────────────────────

    ''' <summary>Total number of times this resource has been downloaded.</summary>
    Public Property DownloadCount As Integer = 0

    ''' <summary>Path to the resource thumbnail image.</summary>
    Public Property ThumbnailPath As String = String.Empty

    ''' <summary>Current version number (increments on every edit).</summary>
    Public Property CurrentVersion As Integer = 1

    ''' <summary>Returns the sum of views and downloads.</summary>
    Public ReadOnly Property TotalEngagement As Integer
        Get
            Return ViewCount + (DownloadCount * 2) ' Downloads carry more weight
        End Get
    End Property

    ''' <summary>
    ''' Returns True if this resource has high engagement.
    ''' </summary>
    Public ReadOnly Property IsPopular As Boolean
        Get
            Return TotalEngagement >= 50
        End Get
    End Property

    ''' <summary>
    ''' Returns the access link - prefers URL, falls back to FilePath.
    ''' </summary>
    Public ReadOnly Property AccessLink As String
        Get
            If Not String.IsNullOrWhiteSpace(URL) Then Return URL
            If Not String.IsNullOrWhiteSpace(FilePath) Then Return FilePath
            Return String.Empty
        End Get
    End Property

    ''' <summary>Returns a display-friendly string for list controls.</summary>
    Public Overrides Function ToString() As String
        Return $"[{ResourceType}] {Title} - {CategoryName}"
    End Function

End Class
