''' <summary>
''' Represents a registered user of the EduVault system.
''' Supports both Admin and Student roles.
''' </summary>
Public Class User

    ''' <summary>Primary key - auto-generated by SQL Server.</summary>
    Public Property UserID As Integer

    ''' <summary>Unique login identifier for the user.</summary>
    Public Property Username As String

    ''' <summary>SHA-256 hashed password - never stored in plain text.</summary>
    Public Property PasswordHash As String

    ''' <summary>Full display name of the user.</summary>
    Public Property FullName As String

    ''' <summary>Optional email address for the user.</summary>
    Public Property Email As String

    ''' <summary>
    ''' Role of the user within the system.
    ''' Valid values: "Admin" | "Student"
    ''' </summary>
    Public Property Role As String

    ''' <summary>Indicates whether the account is active and can log in.</summary>
    Public Property IsActive As Boolean

    ''' <summary>Date and time when the account was created.</summary>
    Public Property DateCreated As DateTime

    ' ─────────────────────────────────────────────────────────────
    ' V2 SECURITY & PERSONALISATION
    ' ─────────────────────────────────────────────────────────────

    ''' <summary>Number of consecutive failed login attempts.</summary>
    Public Property FailedLoginCount As Integer = 0

    ''' <summary>If not Nothing, the user is blocked from logging in until this time.</summary>
    Public Property LockoutEndTime As DateTime? = Nothing

    ''' <summary>Timestamp of the last successful login.</summary>
    Public Property LastLoginDate As DateTime? = Nothing

    ''' <summary>Temporary token for password reset.</summary>
    Public Property PasswordResetToken As String = Nothing

    ''' <summary>Expiration time for the reset token.</summary>
    Public Property ResetTokenExpiry As DateTime? = Nothing

    ''' <summary>True if the user has confirmed their email address.</summary>
    Public Property EmailVerified As Boolean = False

    ''' <summary>FK to tblCategories for notification targeting.</summary>
    Public Property FavouriteCategory As Integer? = Nothing

    ''' <summary>User preference for Light (False) or Dark (True) theme.</summary>
    Public Property DarkMode As Boolean = False

    ''' <summary>Returns True if the account is currently locked out.</summary>
    Public ReadOnly Property IsLockedOut As Boolean
        Get
            Return LockoutEndTime.HasValue AndAlso LockoutEndTime.Value > DateTime.Now
        End Get
    End Property

    ' ─────────────────────────────────────────────────────────────
    ' HELPERS
    ' ─────────────────────────────────────────────────────────────

    ''' <summary>
    ''' Returns True if this user has administrative privileges.
    ''' Admins can add, edit, and delete resources and manage users.
    ''' </summary>
    Public ReadOnly Property IsAdmin As Boolean
        Get
            Return String.Equals(Role, "Admin", StringComparison.OrdinalIgnoreCase)
        End Get
    End Property

    ''' <summary>Returns a display-friendly string for this user.</summary>
    Public Overrides Function ToString() As String
        Return $"{FullName} ({Username}) - {Role}"
    End Function

End Class
